// Generated by gencpp from file robot_pkg/Encoders.msg
// DO NOT EDIT!


#ifndef ROBOT_PKG_MESSAGE_ENCODERS_H
#define ROBOT_PKG_MESSAGE_ENCODERS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_pkg
{
template <class ContainerAllocator>
struct Encoders_
{
  typedef Encoders_<ContainerAllocator> Type;

  Encoders_()
    : header()
    , enc_left(0)
    , enc_right(0)  {
    }
  Encoders_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , enc_left(0)
    , enc_right(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _enc_left_type;
  _enc_left_type enc_left;

   typedef uint32_t _enc_right_type;
  _enc_right_type enc_right;





  typedef boost::shared_ptr< ::robot_pkg::Encoders_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_pkg::Encoders_<ContainerAllocator> const> ConstPtr;

}; // struct Encoders_

typedef ::robot_pkg::Encoders_<std::allocator<void> > Encoders;

typedef boost::shared_ptr< ::robot_pkg::Encoders > EncodersPtr;
typedef boost::shared_ptr< ::robot_pkg::Encoders const> EncodersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_pkg::Encoders_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_pkg::Encoders_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_pkg::Encoders_<ContainerAllocator1> & lhs, const ::robot_pkg::Encoders_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.enc_left == rhs.enc_left &&
    lhs.enc_right == rhs.enc_right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_pkg::Encoders_<ContainerAllocator1> & lhs, const ::robot_pkg::Encoders_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_pkg::Encoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_pkg::Encoders_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_pkg::Encoders_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_pkg::Encoders_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_pkg::Encoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_pkg::Encoders_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_pkg::Encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fa5222877dbcfb0e51225cee374cf9a";
  }

  static const char* value(const ::robot_pkg::Encoders_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fa5222877dbcfb0ULL;
  static const uint64_t static_value2 = 0xe51225cee374cf9aULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_pkg::Encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_pkg/Encoders";
  }

  static const char* value(const ::robot_pkg::Encoders_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_pkg::Encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint32 enc_left\n"
"uint32 enc_right\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_pkg::Encoders_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_pkg::Encoders_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.enc_left);
      stream.next(m.enc_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoders_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_pkg::Encoders_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_pkg::Encoders_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "enc_left: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.enc_left);
    s << indent << "enc_right: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.enc_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PKG_MESSAGE_ENCODERS_H
